### ISSUE TITLE
Add missing meta data and make share cards

### ISSUE THREAD

**Issue by gravem** [gravem/dnd-monster-lookup#24]

**Comment by AyushRawat1718** [comment]
Assign this issue to me, wanna try this

**Comment by gravem** [comment]
Hello there @AyushRawat1718.
I did not expect anyone to come across this. Give it a go. 
The meta data should be tested against various social media meta data readers like https://developers.facebook.com/tools/debug/ and https://www.linkedin.com/post-inspector/

**Comment by gravem** [comment]
@AyushRawat1718 
When you write the meta data, think about making it something a dungeon master wants to use. Here is the mental pitch I have for this project:
Title: Quickly find the monster you are looking for.
Description: This page is your magic item of monster finding. No clutter, just find that monster!
Image: Maybe a printscreen of the page, and fit to the normal share image format. I believe it is 1200px * 630px for facebook.

**Comment by gravem** [comment]
Hey, @AyushRawat1718. I'm sorry, but I want this done so I can share it online today, so I'm taking it. Feel free to keep an eye out for other issues you want to try your hand on.
